# Generated by Django 3.0.7 on 2020-08-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_auto_20200828_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='newness',
            field=models.BooleanField(default=False, verbose_name='Новая'),
        ),
        migrations.AddField(
            model_name='gift',
            name='url',
            field=models.SlugField(default=1, max_length=130, unique=True),
            preserve_default=False,
        ),
    ]
