# Generated by Django 3.0.7 on 2020-09-17 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0006_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_comments', to='gifts.Gift', verbose_name='Дар'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='gifts.Comment', verbose_name='Родитель'),
        ),
    ]
